defaults: &defaults
  HOST: #Hosting URL of peatio (eg. "http://localhost:3000")
  REDIS_URL:      #redis://127.0.0.1:6379
  REDIS_PASSWORD: ~ # By default no password is sent to Redis server. Change this if you want to connect using password.

  # Customize title of markers page using the variable below:
  TITLE_MARKETS: PEATIO

  METADATA_TITLE:       Peatio Exchange
  METADATA_DESCRIPTION: The Opensource Cryptocurrency Exchange
  METADATA_KEYWORDS:    Peatio,Opensource,Exchange,Cryptocurrency

  # Configuration variables for Sentry.
  SENTRY_DSN_FRONTEND: ~         # Specify Sentry DSN used for JavaScript application.

development:
  <<: *defaults

production:
  <<: *defaults
